### ISSUE TITLE
Implement automatic refresh of Cognito authentication token

### ISSUE THREAD

**Issue by collinss-jpl** [NASA-PDS/data-upload-manager#104]
### 💡 Description

The authentication token returned from Cognito has a default expiration of 1 hour, which is typically shorter than what is expected for large file transfers. Cognito authentication tokens can be refreshed by providing the "refresh" token that is supplied after initial authentication.

The DUM client script needs to be updated to support an automatic refresh of the authentication token based on when the token is expected to expire. This should allow long running transfers to complete without interruption.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl is doing last tests on this feature, should be ready for PR later today.
