### ISSUE TITLE
Develop IaC for Deployment

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/data-upload-manager#12]
## 💡 Description

Develop the necessary documentation, terraform scripts and/or other definitions/scripts needed to deploy the app on a user system and deploying to the cloud.

**Comment by jordanpadams** [comment]
📆 June status: Start delayed 2 weeks, but no impact on build expected.

**Comment by jordanpadams** [comment]
📆 July status: Delayed start, but in work. Expected completion by delivery.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl is going to test the terraform scripts on NGAP.

**Comment by tloubrieu-jpl** [comment]
the lambda function is almost terraformed. Everything works well with that.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl is now parameterizing the terraform scripts to be able to deploy on 
NGAP or MCP.

**Comment by jordanpadams** [comment]
📆 August status: In work. Should be completed by end of month.

**Comment by tloubrieu-jpl** [comment]
1/3 done.

**Comment by tloubrieu-jpl** [comment]
All terraform script done, some need to be tested. Should be fully done by the end of the week.
