### ISSUE TITLE
Investigate integration of authentication Lambda/Cognito with API Gateway

### ISSUE THREAD

**Issue by collinss-jpl** [NASA-PDS/data-upload-manager#16]
Ticket to track integration of Cognito authentication with API gateway via Lambda authorizer function.

The following links were provided as a starting point to investigate this feature:

https://github.com/unity-sds/unity-cs/wiki/Getting-Cognito-JWT-Tokens-in-Command-Line
https://github.com/unity-sds/unity-cs-security/tree/main/code_samples

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl was able to test the cognito user pool and tokens. He has a few questions for @ramesh-maddegoda
