### ISSUE TITLE
Develop Ingress Client Logging Capabilities

### ISSUE THREAD

**Issue by collinss-jpl** [NASA-PDS/data-upload-manager#21]
## 💡 Description
Ticket to develop the logging capabilities of the pds-ingress-client.py script. Added capabilities should include:

- [x] Addition of a logging or log utility module to control initialization of the global logger object
- [x] Implement features to allow control of the logging level/format from the command line
- [x] Addition of an API Gateway endpoint to submit client logs to a CloudWatch log group
- [x] Implement submission of all logged information during client execution to the API Gateway endpoint

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl will make progress on that next week
