### ISSUE TITLE
As a user, I want to parallelize upload of data products to PDC

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/data-upload-manager#24]
### Checked for duplicates

Yes - I've already checked

### 💪 Motivation

...so that I can [why do you want to do this?]

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by nutjob4life** [comment]
@nutjob4life had 1 comment on the PR; addressed. A few more improvements pushed, and it's good-to-go now.

**Comment by gxtchen** [comment]
The user document https://nasa-pds.github.io/data-upload-manager returns 404.
I need help on how to test this ticket.
