### ISSUE TITLE
Upload test data set with manual trigger of Nucleus

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/data-upload-manager#31]
## 💡 Description

- [ ] Needs new IAM roles for DUM. To get help from @sjoshi-jpl @viviant100 
- [ ] Test out deployment to MCP
- [ ] Test uploading data from internal pdsmcp-dev EC2 that can reach private API Gateway
  - [ ] Ask SAs to help setup EC2 and give access to specific EN operator user group
- [ ] Test uploading data from on-prem EC2 instance to public API Gateway
  - [ ] Ask SAs to setup IP whitelist
- [ ] Move onto deploying and running with SBN: https://github.com/NASA-PDS/data-upload-manager/issues/32

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl is blocked because of missing IAM roles on MCP (a ticket has been opened).

**Comment by tloubrieu-jpl** [comment]
Client machine has been created on MCP.
@collinss-jpl tested it but it cannot access the API gateway yet. A policy need to be updated.

**Comment by jordanpadams** [comment]
@collinss-jpl tagged up with Sagar to test out but ran into same issue with deploying API Gateway. JPL SAs don't know what is wrong. Gabe at MCP doesn't know what's wrong either. Opened a ticket with AWS.

**Comment by jordanpadams** [comment]
Status: Grabbed a subset of calibration data files (last 4 months)

**Comment by jordanpadams** [comment]
Demo completed on 10/27. Manual trigger not required.
