### ISSUE TITLE
As a user, I want to include a MD5 checksum in the the user-defined object metadata being sent in the upload payload

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/data-upload-manager#50]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Archivist

### 💪 Motivation

...so that I can include a checksum with the files being uploaded to ensure data integrity as the files flow through the system

### Acceptance Criteria

**Given** a file to be uploaded to S3
**When I perform** data upload manager execution on that file
**Then I expect** data upload manager to generate a checksum and add to the object metadata for the S3 object

### ⚙️ Engineering Details

https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html

**Comment by jordanpadams** [comment]
status: implementation planned to be completed by Thursday.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl we need the md5sum of the file which was on the client file system, to track if there was a corruption of the file during the upload. That should be in the metadata of each s3 object, I am re-opening this ticket.

**Comment by collinss-jpl** [comment]
Hi @tloubrieu-jpl, understood. It should be possible to include the client-generated MD5 digest with the pre-signed URL as a header field to accomplish this. I will work on this next.
