### ISSUE TITLE
DUM client is unable to create CloudWatch Log Stream pds-ingress-client-sbn-* when upload data to cloud

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/data-upload-manager#75]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When the css data was uploaded to cloud via DUM client, the following error occured:

WARNING:root:Unable to submit to CloudWatch Logs, reason: Failed to create CloudWatch Log Stream pds-ingress-client-sbn-1709312322, reason: 403 Client Error: Forbidden for url: https://yofdsuex7g.execute-api.us-west-2.amazonaws.com/prod/createstream

### 🕵️ Expected behavior

NO errors. And logs get pushed to the cloud

### 📜 To Reproduce

Run DUM on any data and push data to the cloud.

### 🖥 Environment Info

Linux OS

### 📚 Version of Software Used

0.3.0

### 🩺 Test Data / Additional context

Any PDS4 data

### ⚙️ Engineering Details

As a workaround, let's plan to comment out the code that is causing this for the time being. Logging into AWS is a lower priority ("should") requirement.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl per the Engineering Details above, do you think you could poke through here and just comment out where we initialize this logging?

@collinss-jpl any way you could poke through real quick and identify in the code where we can disable logging to AWS for the time being until we can debug this?

**Comment by collinss-jpl** [comment]
@jordanpadams Commenting the following line out should be sufficient to disable attempts to upload logs to AWS: https://github.com/NASA-PDS/data-upload-manager/blob/main/src/pds/ingress/util/log_util.py#L249

**Comment by tloubrieu-jpl** [comment]
Thanks @collinss-jpl , @jordanpadams , I will do that now.

**Comment by tloubrieu-jpl** [comment]
This ticket will be worked on when Scott comes back.

**Comment by tloubrieu-jpl** [comment]
This is not easy to debug. @collinss-jpl will look at that by comparing with the dev deployment which hopefully still works.

**Comment by tloubrieu-jpl** [comment]
The cache of the api-gateway interfere with the expected behavior. This is now solved, to be confirmed with the next deployment.

**Comment by tloubrieu-jpl** [comment]
We need to discuss with the SA's how to have the API gateway private but accessible from internet. In this case we need a proxy (cloudfront ?) to be in front of the API gateway to expose it to internet.

**Comment by tloubrieu-jpl** [comment]
That sounds ok to have a regional API gateway but:
- we need WAF to be activated on the API gateway
- we need to have a clean DNS/URL to present to the users.

Cloudfront is cheaper than API gateway but in this case we need API gateway anyway.

That is ok to keep the API getaway regional with Cognito.
We should add a resource policy to only authorize IP of known partners as we do for OpenSearch access.
