### ISSUE TITLE
Develop Ingress Client Interface

### ISSUE THREAD

**Issue by collinss-jpl** [NASA-PDS/data-upload-manager#8]
## 💡 Description
The current command-line interface for the Ingress client script only allows a user to provide a single file path, as well as an (arbitrary) node ID. This interface needs to be developed to allow at a minimum:

- Validation of the provided node ID against the standard set of PDS identifiers
- Support for specifying multiple input paths
- Support for distinguishing paths to files vs. paths to directories and performing the appropriate S3 sync logic

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl is finalizing this ticket by adding a feature to preserve the structure of the input archive .

**Comment by jordanpadams** [comment]
Status: Awaiting PR review
