### ISSUE TITLE
Upgrade SBN to latest and Rename Bucket Folder

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/data-upload-manager#97]
### 💡 Description

- [x] Tag new DUM within logging fixed
- [x] Deploy to production
- [x] Request SBN to upgrade
- [x] Rename root folder in S3 bucket from `SBN` to `sbn` (created `sbn` folder, move `gbo...` to `sbn` folder.

**Comment by viviant100** [comment]
v1.1.0 has deployed to production and tested by SBN-PSI.  Will create another ticket for v1.2.0 deployment.
