### ISSUE TITLE
As a user, I want an end summary report in logs to show statistics of files uploaded

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/data-upload-manager#98]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Node Operator

### 💪 Motivation

...so that I can have a summary of how things were uploaded

### 📖 Additional Details

- files uploaded
- files skipped
- files overwritten

### Acceptance Criteria

**Given** a set of files to be uploaded to S3
**When I perform** a nominal upload
**Then I expect** a final report to be output show metrics of files read, files successfully uploaded, files skipped, and files overwritten

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl is now generated a long and short summaries. This has been manually tested.

One issue came up, with the token expiring during the upload process. @collinss-jpl will create a ticket for that issue and make that a priority.
